services:
  mongo:
    image: mongo:latest
    container_name: mongo-database
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-database-volumes:/data/db
    networks:
      - app-network

  mongo-express:
    image: mongo-express:1.0
    container_name: mongo-express
    restart: always
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo-database
    volumes:
      - mongo-express-data-volumes:/root/.config
    depends_on:
      - mongo
    networks:
      - app-network
  
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: app
    image: loggingapp:latest
    stdin_open: true  
    tty: true 
    depends_on:
      - mongo
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
    networks:
      - app-network
  
  test:
    build:
      context: .
      dockerfile: tests/Dockerfile.tests
    container_name: app-tests
    stdin_open: true  
    tty: true
    depends_on:
      - app
    networks:
      - app-network

volumes:
  mongo-database-volumes: {}
  mongo-express-data-volumes: {}

networks:
  app-network:
    external: true